spring.application.name=byteFood


spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}

#Jaeger full tracking(1.0)
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:0.1}
management.otlp.tracing.endpoint=http://jaeger:4318/v1/traces

spring.data.redis.host=redis-device-auth
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}

spring.jpa.defer-datasource-initialization=true

spring.jackson.deserialization.fail-on-unknown-properties=true

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto= ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url= ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bytefood}
spring.datasource.username= ${POSTGRES_USER}
spring.datasource.password= ${POSTGRES_PASSWORD}
spring.security.jwt.secret-key=${JWT_SECRET_KEY}

spring.datasource.driver-class-name=org.postgresql.Driver

app.security.cors-allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:8080}

spring.security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}


